CREATE TABLE customer(
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(64) NOT NULL,
    last_name VARCHAR(64),
    phone_number VARCHAR(16),
    address VARCHAR(256),
    PRIMARY KEY (customer_id)
);

CREATE TABLE price(
    price_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    stock_item_id BIGINT,
    price DECIMAL(16, 2) NOT NULL,
    PRIMARY KEY (price_id),
    FOREIGN KEY (stock_item_id) REFERENCES stock ON DELETE CASCADE
);

CREATE TABLE sale(
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT,
    price DECIMAL(16, 2),
    PRIMARY KEY(customer_id),
    FOREIGN KEY(product_id) REFERENCES product ON DELETE SET NULL
);