volumes:
  postgres-data:
  rabbitmq-data:

services:
  postgres:
    image: postgres:16.2-alpine3.19
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB}
  rabbitmq:
    image: rabbitmq:3.13.1-alpine
    ports:
      - 5673:5672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  migration:
    image: com.eclub/migration:${MIGRATION_VERSION}
    command: -user=eclub -password=eclub -url=jdbc:postgresql://postgres:5432/${DB} migrate
    depends_on:
      - postgres
  sales:
    image: com.eclub/purchases:${PURCHASES_VERSION}
    ports:
      - 8085:8081
    environment:
      - DB=${DB}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - RABBIT_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - migration
  purchases:
    image: com.eclub/purchases:${SALES_VERSION}
    ports:
      - 8086:8080
    environment:
      - DB=${DB}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - RABBIT_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - migration

networks:
  default:
    driver: bridge
