CREATE TABLE product (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(256) NOT NULL,
    vendor VARCHAR(256),
    description TEXT,
    PRIMARY KEY(product_id)
);

CREATE TABLE stock (
    stock_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    batch_number BIGINT NOT NULL,
    quantity INT,
    PRIMARY KEY (stock_item_id),
    FOREIGN KEY (product_id) REFERENCES product,
    CONSTRAINT unique_product_id_batch_number UNIQUE(product_id, batch_number)
);