spring:
  application:
    name: purchases
  rabbitmq:
    host: ${RABBIT_HOST}

db:
  name: ${DB}
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  host: ${DB_HOST}

stock-queue:
  name: stock.transactions
  routing-key: stock.transactions