spring:
  application:
    name: purchases

db:
  name: eclub
  username: eclub
  password: ${DB_PASSWORD}
  host: ${DB_HOST}

stock-queue:
  name: stock.transactions
  routing-key: stock.transactions