spring:
  application:
    name: sales
  rabbitmq:
    host: ${RABBIT_HOST}
    listener:
      type: direct
      direct:
        default-requeue-rejected: false

server:
  port: 8081

db:
  name: eclub
  username: eclub
  password: ${DB_PASSWORD}
  host: ${DB_HOST}

stock-queue:
  name: stock.transactions
  routing-key: stock.transactions