spring:
  application:
    name: sales
  rabbitmq:
    host: ${RABBIT_HOST}
    listener:
      type: direct
      direct:
        default-requeue-rejected: false
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}/${DB}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

stock-queue:
  name: stock.transactions
  routing-key: stock.transactions