spring:
  application:
    name: sales
  rabbitmq:
    host: ${RABBIT_HOST}
    listener:
      type: direct
      direct:
        default-requeue-rejected: false

db:
  name: ${DB}
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  host: ${DB_HOST}

stock-queue:
  name: stock.transactions
  routing-key: stock.transactions